const ResourceActionType = {
  FETCH_ALL_RESOURCES: "FETCH_ALL_RESOURCES",
  FETCH_SINGLE_RESOURCE: "FETCH_SINGLE_RESOURCE",
  DELETE_RESOURCE: "DELETE_RESOURCE",
  EDIT_RESOURCE: "EDIT_RESOURCE",
  ADD_RESOURCE: "ADD_RESOURCE",
};

export default ResourceActionType;
