const GroupActionType = {
    FETCH_ASSIGNMENT_GROUPS: "FETCH_ASSIGNMENT_GROUPS",
    FETCH_USER_ASSIGNMENTS: "FETCH_USER_ASSIGNMENTS",
    ADD_GROUP: "ADD_GROUP",
    REMOVE_GROUP_MEMBER: "REMOVE_GROUP_MEMBER"
};
  
export default GroupActionType;