const AssignmentsStatusActionType = {
    FETCH_ALL_ASSIGNMENTS_STATUS: "FETCH_ALL_ASSIGNMENTS_STATUS",
    FETCH_SINGLE_ASSIGNMENT_STATUS: "FETCH_SINGLE_STATUS",
    FETCH_STUDENT_ASSIGNMENTS_STATUS: "FETCH_STUDENT_ASSIGNMENTS_STATUS",
    EDIT_ASSIGNMENT_STATUS: "EDIT_ASSIGNMENT_STATUS",
    ADD_ASSIGNMENT_STATUS: "ADD_ASSIGNMENT_STATUS",
  };
  
export default AssignmentsStatusActionType;