const AssignmentActionType = {
  FETCH_ALL_ASSIGNMENTS: "FETCH_ALL_ASSIGNMENTS",
  FETCH_SINGLE_ASSIGNMENT: "FETCH_SINGLE_ASSIGNMENT",
  DELETE_ASSIGNMENT: "DELETE_ASSIGNMENT",
  EDIT_ASSIGNMENT: "EDIT_ASSIGNMENT",
  ADD_ASSIGNMENT: "ADD_ASSIGNMENT",
};

export default AssignmentActionType;
