const AttendanceActionType = {
  FETCH_ATTENDANCE: "FETCH_ATTENDANCE",
  FETCH_USER_ATTENDANCE: "FETCH_USER_ATTENDANCE",
  EDIT_ATTENDANCE: "DELETE_ATTENDANCE",
  ADD_ATTENDANCE: "ADD_ATTENDANCE",
};

export default AttendanceActionType;
