const AttendanceActionType = {
  FETCH_ATTENDANCE: "FETCH_ATTENDANCE",
  FETCH_USER_ATTENDANCE: "FETCH_USER_ATTENDANCE",
  EDIT_ATTENDANCE: "EDIT_ATTENDANCE",
  ADD_ATTENDANCE: "ADD_ATTENDANCE",
  CLEAR_ATTENDANCE: "CLEAR_ATTENDANCE",
};

export default AttendanceActionType;
