const UserActionType = {
  FETCH_ALL_USERS: "FETCH_ALL_USERS",
  FETCH_SINGLE_USER: "FETCH_SINGLE_USER",
  DELETE_USER: "DELETE_USER",
  EDIT_USER: "EDIT_USER",
  ADD_USER: "ADD_USER",
  AUTH_USER: "AUTH_USER",
  LOGOUT_USER: "LOGOUT_USER",
};

export default UserActionType;
