const HelpRequestActionType = {
  FETCH_ALL_HELP_REQUESTS: "FETCH_ALL_HELP_REQUESTS",
  FETCH_SINGLE_HELP_REQUEST: "FETCH_SINGLE_HELP_REQUEST",
  DELETE_HELP_REQUEST: "DELETE_HELP_REQUEST",
  EDIT_HELP_REQUEST: "EDIT_HELP_REQUEST",
  ADD_HELP_REQUEST: "ADD_HELP_REQUEST",
};

export default HelpRequestActionType;
